charts/plex/Chart.yaml
charts/plex/templates/deployment.yaml

The deployment template references `.Values.certificate.pkcsMangler.plexPreferences.customCertificateDomain` instead of `.Values.certificate.pkcsMangler.setPlexPreferences.customCertificateDomain`.

[plex] Fix values reference for "customCertificateDomain"

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md

This adds support for pre-commit. It will run the chart-test lint before creating the commit, potentially reducing the number of linting failures in the pipeline.

Add pre-commit support

---

charts/media-common/Chart.yaml
charts/media-common/README.md
charts/media-common/ci/ct-values.yaml
charts/media-common/templates/_helpers.tpl
charts/media-common/templates/addon-openvpn.yaml
charts/media-common/templates/deployment.yaml
charts/media-common/templates/statefulset.yaml
charts/media-common/values.yaml

Adds `media-common-openvpn` add-on to `media-common`. Lays the foundation for migrating helm charts (#37) that use a VPN sidecar to the new media-common chart.
**Note** this PR depends on #46 being merged

[media-common] Add openvpn add-on

---

charts/prometheus-nut-exporter/.helmignore
charts/prometheus-nut-exporter/Chart.yaml
charts/prometheus-nut-exporter/README.md
charts/prometheus-nut-exporter/templates/NOTES.txt
charts/prometheus-nut-exporter/templates/_helpers.tpl
charts/prometheus-nut-exporter/templates/deployment.yaml
charts/prometheus-nut-exporter/templates/service.yaml
charts/prometheus-nut-exporter/templates/serviceaccount.yaml
charts/prometheus-nut-exporter/templates/servicemonitor.yaml
charts/prometheus-nut-exporter/values.yaml

This PR adds support for [prometheus-nut-exporter](https://github.com/HON95/prometheus-nut-exporter).
It can be used to send remote NUT server metrics to a Prometheus instance for monitoring.

[prometheus-nut-exporter] New chart

---

charts/home-assistant/Chart.yaml
charts/home-assistant/values.yaml

[home-assistant] Bump Home Assistant to 0.115.2

---

charts/statping/Chart.yaml
charts/statping/templates/service.yaml

values.yaml has service.annotations but they didn't work completely, which rendered automatic provisioning of load balancers impossible (e.g. DigitalOcean requires specific annotations for HTTPS/SSL configuration). Now it works as intended.

[statping] Allow annotations in service

---

charts/intel-gpu-plugin/.helmignore
charts/intel-gpu-plugin/Chart.yaml
charts/intel-gpu-plugin/README.md
charts/intel-gpu-plugin/templates/_helpers.tpl
charts/intel-gpu-plugin/templates/daemonset.yaml
charts/intel-gpu-plugin/templates/serviceaccount.yaml
charts/intel-gpu-plugin/values.yaml

[intel-gpu-plugin] New chart

---

charts/adguard-home/Chart.yaml
charts/adguard-home/templates/service-dhcp.yaml
charts/adguard-home/templates/service-dns-over-tls.yaml
charts/adguard-home/templates/service-tcp.yaml
charts/adguard-home/templates/service-udp.yaml
charts/adguard-home/templates/service.yaml
charts/adguard-home/values.yaml

Adds additional parameters to be set on services (externalIPs, etc)

[adguard-home] enable additional service options

---

charts/media-common/Chart.yaml
charts/media-common/templates/ingress.yaml

Signed-off-by: Waldemar Faist <cubic@coldice.net>
Currently HELM is not able to process the chart if `extraIngresses` is used:
```
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: [stripped local path]/radarr
Error: template: radarr/charts/radarr/templates/ingress.yaml:67:8: executing "radarr/charts/radarr/templates/ingress.yaml" at <include "media-common.labels" .>: error calling include: template: radarr/charts/radarr/templates/_helpers.tpl:38:18: executing "media-common.labels" at <include "media-common.chart" .>: error calling include: template: radarr/charts/radarr/templates/_helpers.tpl:31:25: executing "media-common.chart" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm.go:94: [debug] template: …
```

[media-common] Fixes HELM error on extraIngresses

---

charts/frigate/Chart.yaml
charts/frigate/values.yaml
charts/home-assistant/Chart.yaml
charts/home-assistant/values.yaml
charts/plex/Chart.yaml
charts/plex/values.yaml
charts/teslamate/Chart.yaml
charts/teslamate/values.yaml

* friagte: 0.6.0
* home-assistant: 0.116.1
* plex: 1.20.2.3402-0fec14d92
* teslamate: 1.20.0
Additionally, also needed to remediate the `teslamate` chart to use the bitnami postgres subchart instead of the (now deprecated) helm/charts postgres chart.  testlamate wouldn't properly install until this was done.

[multiple] Bump various chart image versions

---

charts/jackett/Chart.yaml
charts/lidarr/Chart.yaml
charts/nzbget/Chart.yaml
charts/ombi/Chart.yaml
charts/organizr/Chart.yaml
charts/qbittorrent/Chart.yaml
charts/radarr/Chart.yaml
charts/sonarr/Chart.yaml
charts/tautulli/Chart.yaml

Signed-off-by: Waldemar Faist <cubic@coldice.net>
@carpenike Looks like charts that are depending on `media-common` are not rebuilt using the patch in #84. Haven't take a look in the CI settings on this project. This would require to bump a a patch version on all charts using `media-common`, since the charts use `^1.0.0` as dependent version. Thanks ;)

[media-common] Bump charts depending on media-common

---

charts/home-assistant/Chart.yaml

Signed-off-by: nolte <nolte07@googlemail.com>
Update Chart Version from esphome to [2.2.0](https://github.com/k8s-at-home/charts/releases/tag/esphome-2.2.0), for arm support.

[home-assistant] pump up esphome chart version

---

charts/zwave2mqtt/Chart.yaml
charts/zwave2mqtt/README.md
charts/zwave2mqtt/templates/deployment.yaml

Based on the developers this volume does not need to be persistent if we enable `auto update device db`
Fixes: #5 

[zwave2mqtt] Remove the persistent /usr/local/etc/openzwave volume

---

charts/zigbee2mqtt/Chart.yaml
charts/zigbee2mqtt/templates/statefullset.yaml
charts/zigbee2mqtt/values.yaml

This allows to add extra environment variables and mount extra volumes in the zigbee2mqtt pod, for example TLS files or config overrides (ZIGBEE2MQTT_CONFIG_ environment).

[zigbee2mqtt] add extraEnv etc., extraVolumes & extraVolumeMounts

---

charts/mosquitto/Chart.yaml
charts/mosquitto/templates/statefullset.yaml
charts/mosquitto/values.yaml

This allows to mount extra volumes in the mosquitto pod, for example TLS or password file secrets.

[mosquitto] add extraVolumes & extraVolumeMounts support

---

.github/workflows/release.yaml

Fixes the "Release Charts" Github workflow.
https://helm.sh/blog/new-location-stable-incubator-charts/

fix stable repo

---

charts/home-assistant/Chart.yaml
charts/home-assistant/README.md
charts/home-assistant/templates/servicemonitor.yaml
charts/home-assistant/values.yaml

I want the ability to drop pod and instance labels for home-assistant metrics
See example in values.yaml

[home-assistant] Added metricRelabelings for service monitor

---

charts/mosquitto/Chart.yaml
charts/mosquitto/ci/sidecar-values.yaml
charts/mosquitto/templates/podmonitor.yaml
charts/mosquitto/templates/service.yaml
charts/mosquitto/templates/statefullset.yaml
charts/mosquitto/values.yaml

Signed-off-by: nolte <nolte07@googlemail.com>
[#100](https://github.com/k8s-at-home/charts/pull/100) as optional Sidecar implementation and, support for create a PodMonitor.
~- [ ] Variables are documented in the README.md~

[mosquitto] add Prometheus Exporter as Sidecar Container

---

charts/unifi/Chart.yaml
charts/unifi/README.md
charts/unifi/templates/deployment.yaml
charts/unifi/templates/promtail-configmap.yaml
charts/unifi/templates/syslog-svc.yaml
charts/unifi/templates/unified-svc.yaml
charts/unifi/values.yaml

This adds two features:
- `syslogService` to capture syslog from Unifi devices (needs to be enabled in site configuration). Logs from Unifi devices will end up in `/unifi/logs/remote`.
- optional Promtail sidecar for controller logs and remote device logs if available

[unifi] syslog & promtail logging

---

charts/common/Chart.yaml
charts/common/templates/addons/vpn/openvpn/_container.tpl
charts/common/templates/addons/vpn/wireguard/_addon.tpl
charts/common/templates/addons/vpn/wireguard/_container.tpl
charts/common/templates/lib/controller/_volumes.tpl
charts/common/values.yaml

- Use the k8s-at-home wireguard image
- Make VPN container securityContext configurable
- Clean up some small indenting/quotation issues

[common] Use k8s-at-home wireguard image

---

charts/common/Chart.yaml
charts/common/templates/classes/_service.tpl
charts/common/templates/classes/_service_ports.tpl
charts/common/templates/lib/controller/_container.tpl
charts/common/templates/lib/controller/_ports.tpl

Should fix #169
One edge case remains but I don't think we should build for it: if multiple ports would have the same name, the container spec will contain duplicate port names, which is not allowed.

[common] Read and the service ports correctly

---

charts/ddclient/.helmignore
charts/ddclient/Chart.yaml
charts/ddclient/OWNERS
charts/ddclient/README.md
charts/ddclient/ci/ct-values.yaml
charts/ddclient/templates/NOTES.txt
charts/ddclient/templates/common.yaml
charts/ddclient/templates/configmap.yaml
charts/ddclient/values.yaml

This takes a free-form config to configure ddclient.

[ddclient] new chart

---

charts/unifi/Chart.yaml
charts/unifi/README.md
charts/unifi/templates/deployment.yaml
charts/unifi/values.yaml

* Add jvmInitHeapSize and jvmMaxHeapSize which are passed on
to the container as env vars
* Bump version, no change in default behaviour
* Update README.md with new configuration parameters
Signed-off-by: Thomas Ingvarsson <ingvarsson.thomas@gmail.com>

[unifi] Add jvmInitHeapSize and jvmMaxHeapSize configuration

---

charts/unifi/Chart.yaml
charts/unifi/templates/deployment.yaml

The recently introduced speedtest service in PR #148 specified the container port inside the conditional for `captivePortalService`. This changes fixes this.

[unifi] Fix speedtest container port

---

.github/ct.yaml
.github/workflows/lint-test.yaml
.github/workflows/release.yaml

- moved `ct.yaml` to `.github` directory
- updated linting workflow and bumped `helm/chart-testing-action` to `v2.0.1`
- updated release workflow and bumped `helm/chart-releaser-action` to `v1.1.0`
- added job after release job to update `generated` timestamp in `index.yaml` in the `gh-pages` branch
Minor issue with `helm/chart-releaser-action` is this issue https://github.com/helm/chart-releaser-action/issues/61 however I didn't see this behavior in our tests

[workflow] update linting and release workflows

---

charts/traefik-forward-auth/Chart.yaml
charts/traefik-forward-auth/README.md
charts/traefik-forward-auth/templates/deployment.yaml
charts/traefik-forward-auth/templates/secret.yaml
charts/traefik-forward-auth/values.yaml

Cookie-secret is normally automatically generated by traefik-forward-auth. But if specified via env-vars, it would allow you to run multiple instances of forward-auth on the same cookie domain, enabling authentication between them without logging in multiple times. 
If this isn't set, and you try and use the same cookie domain; you'd be presented with a "Not Authorized" message as the cookie-secret doesn't match that instance's value, and you'd need to do a `/_oauth/logout` and re-authenticate to set the cookie with the new cookie-secret.
My changes will, if necessary add the env-var to the pod, and create a secret if necessary.  

[traefik-forward-auth] Add cookie secret to values

---

.github/renovate.json

[renovate] remove gitAuthor from renovate config

---

charts/bitwardenrs/Chart.yaml
charts/bitwardenrs/templates/hpa.yaml

Fixes #286 
Confirmed that this change fixes the issue, as I am now seeing the HPA correctly scraping pod metrics.

[bitwardenrs] Fix HPA target

---

charts/appdaemon/Chart.yaml
charts/appdaemon/values.yaml

Mistake on the mountPath, it is defaulted to `/config` in our image.
https://github.com/k8s-at-home/container-images/blob/main/appdaemon/entrypoint.sh#L7

[appdaemon] remove mountPath

---

charts/blocky/Chart.yaml
charts/blocky/templates/deployment.yaml
charts/blocky/templates/persistentvolumeclaim.yaml
charts/blocky/values.yaml

Adds a volume to the blocky deployment for query logs. Can either be an `emptyDir` if persistence is disabled, an existing PVC referenced by `persistence.existingClaim`, or new PVC.
**Benefits**
Allows the use of query logs without filling the pod's ephemeral storage. Persistence is opt-in and will only be used if query logs are enabled.
Only supports a deployment with a referenced PVC for now, using a StatefulSet is not supported. This means that only 1 replica can be used if the access mode is `ReadWriteOnce`. Additionally the PVC will be deleted if the chart is uninstalled.
**Checklist**

[blocky] Update to 0.11 and add query log pvc

---

charts/plex/Chart.yaml
charts/plex/templates/deployment.yaml

Ensure we always use a string and prevent accidental usage of incorrect type
(such as using true or false as values)
**Benefits**
Incorrect value type would lead to templating errors and would require additional escaped quotes. This bypasses those issues and should make it less error-prone to users. 
N/A
- Mentioned in to #137
Pretty simple change
**Checklist**

[plex] Quote values for extraEnv

---

charts/common/CHANGELOG.md
charts/common/Chart.yaml
charts/common/templates/addons/code-server/_container.tpl
charts/common/values.yaml

Enable code-server addon to run with additional configured runtime arguments
**Benefits**
Enables additional runtime features, such as: 
```
--user-data-dir        Path to the user data directory.
--extensions-dir       Path to the extensions directory.
--list-extensions      List installed VS Code extensions.
--force                Avoid prompts when installing VS Code extensions.
--install-extension    Install or update a VS Code extension by id or vsix. The identifier of an extension is `${publisher}.${name}`.
To install a specific version provide `@${version}`. For example: 'vscode.csharp@1.2.3'.
--enable-proposed-api  Enable proposed API features for extensions. Can receive one or more extension IDs to enable individually.
```
As configured currently, …

[common] allow code-server to run with additional args

---

charts/node-feature-discovery/Chart.yaml
charts/node-feature-discovery/values.yaml

According to the new release of node-feature-discovery https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.7.0 the registry moved from `quay.io` to `gcr.io`. I bumped to the new version too. Keep in mind, that there is a PR open in kubernetes-sigs/node-feature-discovery/pull/423 for a hosted chart in its repo.
**Benefits**
Automation will find new images for the deployment.
None.
No related issues.
None.
**Checklist**

[node-feature-discovery] New image repository and version bump to v0.7.0

---

charts/resilio-sync/.helmignore
charts/resilio-sync/Chart.yaml
charts/resilio-sync/OWNERS
charts/resilio-sync/README.md
charts/resilio-sync/templates/NOTES.txt
charts/resilio-sync/templates/common.yaml
charts/resilio-sync/values.yaml

Adding a chart for resilio-sync based on [linuxserver image](https://github.com/orgs/linuxserver/packages/container/package/resilio-sync).
**Checklist**

[resilio-sync]: new chart

---

charts/dsmr-reader/.helmignore
charts/dsmr-reader/Chart.yaml
charts/dsmr-reader/OWNERS
charts/dsmr-reader/README.md
charts/dsmr-reader/ci/ct-values.yaml
charts/dsmr-reader/templates/NOTES.txt
charts/dsmr-reader/templates/common.yaml
charts/dsmr-reader/values.yaml

Adds a chart for [dsmr-reader](https://github.com/dsmrreader/dsmr-reader), a DSMR-protocol reader, telegram data storage and energy consumption visualizer. Can be used for reading the smart meter DSMR (Dutch Smart Meter Requirements) P1 port.
**Benefits**
More charts! 😄 
N/A
N/A
N/A
**Checklist**

[dsmr-reader] New chart

---

charts/home-assistant/Chart.yaml
charts/home-assistant/templates/secret.yaml
charts/home-assistant/values.yaml

Allows setting a Base64-encoded SSH private key
**Benefits**
Using sealed-secrets and `.env` I need to pass this var in as a single line, SSH private keys are multiline
None
- fixes #
**Checklist**

[home-assistant] allow setting a base64-encoded SSH private key

---

charts/blocky/Chart.yaml
charts/blocky/templates/deployment.yaml
charts/blocky/values.yaml

Make sure blocky also runs without having /metrics
And removed some values that didn't do anything
**Benefits**
Without running prometheus still a succesfull deployment
None
None
**Checklist** 
- [] Chart is using our [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library as a dependency.

[Blocky] Change probes to /

---

charts/readarr/.helmignore
charts/readarr/Chart.yaml
charts/readarr/README.md
charts/readarr/templates/NOTES.txt
charts/readarr/templates/common.yaml
charts/readarr/values.yaml

Readarr is a radarr fork for Books, AudioBooks etc. It's still in early development but is lined up to be a replacement for LazyLibrarian. This PR adds the new chart. 
**Benefits**
Whole new charts. 
It's currently only nightly builds as the project is quite new. 
**Checklist**

[Readarr] New Readarr chart

---

charts/octoprint/Chart.yaml
charts/octoprint/values.yaml

Use the built-in haproxy for octoprint, since otherwise the webcam support won't work.
**Benefits**
If not implemented, webcam support will not work by default.
N/A
N/A
**Checklist**

[octoprint] Use built-in haproxy

---

charts/oauth2-proxy/Chart.yaml
charts/oauth2-proxy/README.md
charts/oauth2-proxy/templates/deployment.yaml
charts/oauth2-proxy/values.yaml

This change adds possibility to specify initContainers for oauth-proxy2 pod.
**Benefits**
Example use case is fetching secrets from external source, e.g. with vault-agent fetch secrets from Hashicorp Vault.
None, by default no initContainers are added.
**Checklist**

[oauth2-proxy] Add support for initContainers

---

charts/deluge/.helmignore
charts/deluge/Chart.yaml
charts/deluge/OWNERS
charts/deluge/README.md
charts/deluge/templates/NOTES.txt
charts/deluge/templates/common.yaml
charts/deluge/values.yaml

New chart for the Deluge torrent downloader. 
**Benefits**
Deluge is straightforward, stable, easy use torrent client that can run headless in the cloud. It comes bundled quite often with LazyLibrarian, Sonarr, Radarr etc. A chart for this does not yet exist as far as I am aware. 
None.
None 
**Checklist**

[Deluge] V1 of Deluge Chart

---

charts/nzbhydra2/Chart.yaml
charts/nzbhydra2/values.yaml

Use the HTTP endpoints for readiness, liveness and startup instead of the port. So if anything goes wrong internally in the app these will stop returning 200 and the pod would be considered unhealthy. 
**Benefits**
Better liveness checks than a TCP port check. 
Not aware of any
- fixes #411
**Checklist**

[nzbhydra2] Use HTTP probes & Bump Version

---

charts/powerdns/Chart.yaml

- Bring `appVersion` from `Chart.yaml` back in sync with `image.tag` from `values.yaml`
- `postgres.enabled` -> `postgresql.enabled` for postgresql dependency in `Chart.yaml`
**Checklist**

[powerdns] Fix some minor issues related to #78

---

charts/hyperion-ng/.helmignore
charts/hyperion-ng/Chart.yaml
charts/hyperion-ng/OWNERS
charts/hyperion-ng/README.md
charts/hyperion-ng/templates/NOTES.txt
charts/hyperion-ng/templates/common.yaml
charts/hyperion-ng/values.yaml

New chart!
**Benefits**
This service, along with WLED driver for LED lights and a Hyperion Android app, allows for the sync of TV backlighting to whatever is being played on Android TV
You cover the whole wall with LEDs
None
I have been running this, piggy backing off of the Radarr chart with no issues.
The only things I am not sure about are
- How to name the config data since the path for Hyperion's config is odd. This could be changed by forking the docker build, I suppose
- The docker tag, there are other archs but the images aren't multi-arch. 
**Checklist**

[hyperion-ng] Initial Commit

---

charts/samba/.helmignore
charts/samba/Chart.yaml
charts/samba/OWNERS
charts/samba/README.md
charts/samba/templates/NOTES.txt
charts/samba/templates/common.yaml
charts/samba/values.yaml

New chart for a simple in-cluster samba server.
**Benefits**
Allows running a simple Samba server in the cluster. This can be useful for example when running a Synology / Sonos combination, where Sonos does not support newer Samba versions and Synology does not allow older versions.
N/A
- #437 
This is a simple server chart for now, based completely on the image provided by https://github.com/dperson/samba (because it supports the desired functionality out of the box and can be configured using environment variables.
**Checklist**

[samba] New chart

---

charts/mosquitto/Chart.yaml
charts/mosquitto/templates/NOTES.txt
charts/mosquitto/templates/service.yaml
charts/mosquitto/values.yaml

Updated the service to have configurable ports for users that wish to run on non-standard. 
**Benefits**
Users can configure the ports that they want the service to expose
Tested on microk8s 
**Checklist**

[Mosquitto] Update Mosquitto to support configurable ports

---

charts/zwave2mqtt/Chart.yaml
charts/zwave2mqtt/values.yaml

Add custom probe examples to the zwave2mqtt chart, based on https://github.com/OpenZWave/Zwave2Mqtt#health-check-endpoints
**Benefits**
Get better feedback from the liveness of the application
- fixes #91 
Disabled the probes by default, since the application needs to be configured before the probes would actually work.
**Checklist**

[zwave2mqtt] Custom probes

---

charts/bitwardenrs/Chart.yaml
charts/bitwardenrs/templates/deployment.yaml
charts/bitwardenrs/templates/statefulset.yaml
charts/bitwardenrs/values.yaml

Signed-off-by: TJ Wesolowski <wojoinc@pm.me>
Adds an option to the values.yaml:
```yaml
bitwardenrs:
gui:
port: 80
```
**Benefits**
When combined with the following:
```yaml
env:
ROCKET_PORT: "<port>"
```
this allows the user to specify a different port for bitwarden to bind to for the WebUI.
This has other benefits, but the most significant is that it allows the user to specify a web port above 1024 when running the container as a non-root user. For example, with the following SecurityContext:
```yaml
securityContext:
capabilities:
drop:
- ALL
readOnlyRootFilesystem: true
runAsNonRoot: true
runAsUser: 65534
```
None that I can see so far.
- fixes #491
- Related: dani-garcia/bitwarden_rs#776
**Additional …

[bitwardenrs] Add option to change web port

---

charts/zwavejs2mqtt/Chart.yaml
charts/zwavejs2mqtt/values.yaml

- Default to non-privileged
- No default device mounts
- `envFrom` example
- Ingress example

[zwavejs2mqtt] Safer default values.yaml

---

charts/zigbee2mqtt/Chart.yaml
charts/zigbee2mqtt/values.yaml

Much safer defaults (similar to #493):
- Disabled privileged by default.
- Disabled mounting devices by default. 
- Updated exampled device name to match a more useful case (specific device, not to encourage generic device names)
- Added a comment to check `common` chart.
Additionally:
- Some more options to default configuration, especially useful for Conbee II and/or Home Assistant.

[zigbee2mqtt] Safer default values, improved configuration

---

charts/oauth2-proxy/Chart.yaml
charts/oauth2-proxy/values.yaml

This updates the image repo to https://quay.io/repository/oauth2-proxy/oauth2-proxy and bumps the version to v6.1.1
**Benefits**
I do not see any issues bumping this to v6.1.1, the chart has been working _fine_ for a long time.
Could be an edge case where upgrading to v6.x might break some feature in the chart, but we will cross that road when we get to it :)
- fixes #
**Checklist**

[oauth2-proxy] change image to new home and bump image version

---

charts/powerdns/Chart.yaml
charts/powerdns/templates/deployment.yaml

* Re-add the webserver container port that was removed in a recent change
* Fix post-start script
- don't trim whitespace between `OPTIONS` and `HOST` arguments to `nc` command
- retry loop would always terminate after first attempt; re-formatted and re-structured script for clarity
**Benefits**
* Brings back the webserver port, restoring functionality that had worked in older versions (e.g. v2.2.0)
* Fixes the post-start script, saves users from needing create their zone manually
* Existing users not overriding `powerdns.domain` will now get a `mydomain.local` zone (re-)created for them on upgrade, and all future restarts
- should we make the post-start hook conditional on `powerdns.domain` being set, and change the default to empty …

[powerdns] Webserver container port, and startup script fixes

---

charts/common/CHANGELOG.md
charts/common/Chart.yaml
charts/common/templates/lib/controller/_container.tpl
charts/common/values.yaml

Once we start messing with arguments, it is often convenient to also override the command (which is the container entrypoint). I just hit a use case where that would have been helpful. 
Normal people would never need this, but it is not harmful either. 
Signed-off-by: Ingvarr Zhmakin

[common] Allow to override container command

---

charts/plex/Chart.yaml
charts/plex/templates/deployment.yaml
charts/plex/values.yaml

This change adds the ability to freely use existing network storage (or hostPath storage) not defined as a PV inside the cluster. Eg. I have 2 Synology NFS filer containing various media files. Without this change, I need to define a PV and PVC to use this. Especially defining PVs need cluster admin access, which can be avoided using this ability.
**Benefits**
Freely use existing external storage without defining PVs and PVCs.
`-`
`-`
`-`
**Checklist**

[plex] Add ability to define volume in extraMounts

---

charts/plex/Chart.yaml
charts/plex/templates/deployment.yaml
charts/plex/values.yaml

During the migration from an ubuntu based installation, I needed the ability to disable the Probes, since the listening configs in the migrated config did not serve 200 OK to the kubelet and therefore I was not able to configure plex without `kubectl port-forward`:
```console
$ kubectl exec -ti plex-8f84f474c-r8xx6 -- bash
root@plex-8f84f474c-r8xx6:/# curl http://<Pod IP>:32400/identity
curl: (52) Empty reply from server
root@plex-8f84f474c-r8xx6:/# curl http://127.0.0.1:32400/identity
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0" claimed="1" machineIdentifier="foo" version="1.20.2.3402-0fec14d92">
</MediaContainer>
```
While here, I thought it would be useful, if we have the ability to freely configure the probes through `values.yaml` …

[plex] Add ability to disable and customize probes

---

charts/common-test/Chart.yaml
charts/common-test/ci/statefulset-values.yaml
charts/common/Chart.yaml
charts/common/templates/_statefulset.tpl
charts/common/templates/lib/controller/_container.tpl
charts/common/values.yaml

Adding support for volumeClaimTemplates in statefulset in the common chart
**Benefits**
With this change is possible to use the full power of the statefulset in the common chart, ie it's possible to have unique storage for each instance of a statefulset, and make it possible to scale a statefulset to more than one member.
After removing a helm deployment using this functionality the pvc/pv will be kept.
- fixes #
More information about Statefulset can be found at:
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage
**Checklist** 
- [ x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ x ] Title of the PR starts with …

[common] Add support for volumeClaimTemplates in statefulset

---

charts/common/templates/lib/controller/_pod.tpl
charts/common/values.yaml

Just little stuff which happened to be useful in smarter-device-manager (#490).
**Benefits**
Not harming.
Not rewarding?..
N/A
**Checklist**
- [-] (optional) Variables are documented in the README.md

[common-next] some additional pod properties

---

charts/unifi/Chart.yaml
charts/unifi/templates/captive-ingress.yaml

Add conditional to ingress for captive portal to default to https, otherwise, use http
**Benefits**
Users will be able to use https ingress for captive portal
Might create weird behavior for people with https service enabled for captive portal, but aren't actually using it.
- fixes #539 
**Checklist** 
I didn't bump up the Chart version actually because I didn't change the chart, only the template.  Can someone test this fix? I currently have my unifi controller up on my one node K8S and my ingress uses the node IP, so I can't deploy it again.

[unifi] Added conditional, if https svc for captive portal defined, default to https svc

---

charts/unifi/Chart.yaml
charts/unifi/templates/captive-ingress.yaml

My last PR broke because range seems like it restricted what I could use for values for that section.  I've defined it as a variable at the top of the template and referenced it using that.
Defined the following {{- $captivePortalHttps := .Values.captivePortalService.https -}} so I can use it in a conditional correctly.
**Benefits**
Fixes the broken template
None that weren't already introduced in the last PR #540 
- fixes  #539
I was able to test using dry run so I can confirm it'll go through this time.
**Checklist**

[unifi] Fixed unifi chart breaking from range restriction value on captive ingress

---

charts/unifi/Chart.yaml
charts/unifi/templates/deployment.yaml

Changed the values of the container ports for the captive portal to be dynamic in the deployment like gui and controller.
**Benefits**
It'll allow users using the captive portal in https mode to use standard https port instead of the default 8843.  I couldn't get around the captive portal appending :8843 to my ingress url, messing it up.
None that aren't already exist with setting lit like gui and controller service.
- fixes #
**Checklist**

[unifi] Allow service port to define captive portal port in deployment like gui and controller service

---

charts/unifi/Chart.yaml
charts/unifi/templates/deployment.yaml

#547 incorrectly placed the new env variable wrapped inside a conditional that should not have been; this PR fixes that placement.
**Benefits**
Make stdout logging work
**Checklist**

[unifi] fix typo in UNIFI_STDOUT placement

---

CONTRIBUTING.md

running `chart:create` fails due to missing go-replace; tried on a few different environments.
helm looks to be used later on in `chart:create`, so picked `deps:install` instead of `deps:go-replace`.

install go-replace before using it

---

templates/chart/Chart.yaml

CONTRIBUTING.md says charts should start at 1.0.0; so presumably the template should too.
Fresh charts generated with `task chart:create` start at 1.1.0 because of this line.

shouldn't bump template version

---

charts/common/CHANGELOG.md
charts/common/Chart.yaml
charts/common/values.yaml

**Benefits**
Services will be reported as Ready a lot sooner, minimising downtime.
N/A
- fixes #573 
**Checklist**

[common] v3.0.0

---

charts/sonarr/Chart.yaml

It looks like in September, there was an effort to reorganize the charts. Unfortunately, commit b94814d3d708ce4cf46bb0aafde9178cb5976092 moved the entries for Sonarr but missed this one URL.
**Benefits**
For users working through graphical installers like Rancher, this value is really helpful to have right.
None
n/a
n/a
**Checklist**

[sonarr] chore: fix chart home URL after it was missed

---

.github/workflows/charts-release.yaml

- Flux2 relies less on this field now
- Chart releaser has been updated to generate this timestamp on the next release https://github.com/helm/chart-releaser/issues/90
I think it's safe to remove now even though the new version of the chart releaser action isn't released yet. Renovatebot should notify us of an upgrade to the action.

[actions] remove updating timestamps in index.yaml

---

charts/oauth2-proxy/Chart.yaml
charts/oauth2-proxy/README.md
charts/oauth2-proxy/templates/ingress.yaml
charts/oauth2-proxy/values.yaml

Add support for ingressClassName in oauth2-proxy
**Benefits**
Add support for ingressClassName in oauth2-proxy
N/A
- fixes #449
**Checklist**

[oauth2-proxy] add support for ingressClassName

---

charts/pyload/Chart.yaml
charts/pyload/values.yaml

Simple addition of a sample for the /downloads mount path used by pyload.
Just thought it would be worth to be added to the values.yaml of the pycharm chart :)
See above
**Benefits**
Anyone deploying the chart may not wonder where downloads go ;)
None
-
-
**Checklist**

[pyload] Add /downloads PVC use to pyload chart

---

charts/transmission/Chart.yaml
charts/transmission/README.md
charts/transmission/README_CHANGELOG.md.gotmpl
charts/transmission/templates/common.yaml
charts/transmission/templates/configmap.yaml
charts/transmission/values.yaml

The chart now always uses the chart-defined transmission config
**Benefits**
App config is now idempotent
- fixes #
**Checklist**

[transmission] always use chart-defined config

---

templates/chart/Chart.yaml

remove arguably redundant source line; reducing redundancy
**Benefits**
reducing redundancy
doesn't also remove all the existing redundant lines
> This one is a bit superfluous since it's also the `home` location of the chart
_Originally posted by @bjw-s in https://github.com/k8s-at-home/charts/pull/575#discussion_r580824153_

[meta] remove source line matching chart home in template [ci-skip]

---

.github/workflows/invalid-template.yaml
.github/workflows/support.yaml

- Adds an support workflow, when we label issues with the `support` label, the issue will be closed, and a message posted to the issue.
- Adds an invalid template workflow, when we label issues with the `invalid/template-incomplete` label, the issue will be closed, locked and a message posted to the issue.

[workflows] create issue workflows [ci-skip]

---

charts/plex/Chart.yaml
charts/plex/values.yaml

[plex] fix typos

---

charts/uptimerobot/Chart.yaml
charts/uptimerobot/templates/deployment.yaml

This PR is needed to fix the uptimerobot chart when using `config.influxdb.username` and `config.influxdb.password`. Currently the values get added to the secret uptimerobot but the deployment template references a configmap. But there is not configmap defined in the chart.
**Benefits**
This allows the chart to be deployed when using setting the influxdb creds.
None
#640 
**Checklist**

[uptimerobot] Swapping from configMapKeyRef to secretKeyRef

---

charts/duplicati/Chart.yaml
charts/duplicati/templates/deployment.yaml

Add the possibility to add additional volume mounts for example nfs.
**Benefits**
With this option you are able to mount also nfs shares to duplicati so that you can backup them.
**Checklist**

[duplicati] Add possibility to add additional volume mounts

---

charts/homer/Chart.yaml
charts/homer/README.md
charts/homer/README_CHANGELOG.md.gotmpl
charts/homer/templates/_helpers.tpl
charts/homer/templates/common.yaml
charts/homer/templates/configmap.yaml
charts/homer/values.yaml

Adds the ability to configure homer with a configmap containing the application configuration
**Benefits**
Configure the application with values.yaml
N/A - Backwards compatible for users configuring homer with an alternative method.
N/A
**Checklist**

[homer] configmap support

---

charts/mosquitto/Chart.yaml
charts/mosquitto/README.md
charts/mosquitto/templates/configmap.yaml
charts/mosquitto/values.yaml

Just added optiosn to allow enabling auth and config_directories for further config-options.
**Benefits**
* you will be able to enable auth and use config_dir for further settings.
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X ] Title of the PR starts with chart name (e.g. `[home-assistant]`)

[mosquitto] added auth and config_dir

---

charts/joplin-server/Chart.yaml
charts/tdarr/Chart.yaml

Charts are not uploaded on public repo.
> helm search repo k8s-at-home | grep -i tdarr
> helm search repo k8s-at-home | grep -i joplin
Local installation is working.

[joplin-server][tdarr] Bump to re-trigger repo upload

---

charts/stable/adguard-home/Chart.yaml
charts/stable/adguard-home/templates/deployment.yaml
charts/stable/adguard-home/templates/service.yaml

the goal of the change is to : 
- reflect subpath config in the values.yaml to show in the deployment
**Benefits**
- actually use subpath in volume mounts in the deployment when a user sets this parameter and expects it to work
should be a seamless change for existing users, so can't think of any
None
**Checklist**

[adguard-home] fix  volumes subpath

---

charts/stable/home-assistant/Chart.yaml
charts/stable/home-assistant/values.yaml

Signed-off-by: Fabio Brito d'Araujo e Oliveira <psychopenguin@gmail.com>
Upgrade for home assistant image tag to 2021.3.4
**Benefits**
Latest stable version of Home Assistant - Check changelog at https://www.home-assistant.io/blog/2021/03/03/release-20213/
Check the breaking changes list before upgrade: https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes
**Checklist**

[home-assistant] upgrade image tag to 2021.3.4

---

charts/stable/ddclient/Chart.yaml
charts/stable/digitalocean-dyndns/Chart.yaml

deprecate both digitalocean-dyndns and ddclient charts
**Benefits**
It's a much more elegant solution to use a k8s CronJob to do this, rather then support charts for any providers dyndns chart.
I have laid out a guide below on how to use a configmap, secret and cronjob to accomplish this task. We should point people to it when asked or issues are raised relating on how to handle dyndns in your cluster
https://docs.k8s-at-home.com/guides/dyndns/
We could perhaps support a chart that wires this up automagically, but it might be hard because of all the different DNS APIs
**Checklist**

[digitalocean-dyndns/ddclient] deprecate charts

---

charts/stable/teslamate/Chart.yaml
charts/stable/teslamate/values.yaml

Update the default teslamate container image to latest (1.22.0)
**Benefits**
Fixes login issues with Tesla API servers which requires a new version of Teslamate.
Ref #715 and #716  originally submitted by @EasternPA
**Checklist**

[teslamate] - bump teslamate default image to 1.22.0

---

charts/stable/valheim/Chart.yaml
charts/stable/valheim/values.yaml

The default resource settings from the common lib chart aren't adequate enough for the resources needed for the valheim container.  This change sets reasonable CPU & memory requests/limits for running this particular workload.
**Benefits**
This will prevent OOMkills of valheim when deploying the chart
Kubernetes will not be able to schedule this chart if there are not enough resources.
Data collected from Prometheus about the actual CPU & memory usage of the valheim chart supporting this change:
**Checklist**

[valheim] - set realistic resource defaults for valheim

---

charts/stable/rtorrent-flood/Chart.yaml
charts/stable/rtorrent-flood/templates/configmap.yaml

This should fix the issue of `.rtorrent.rc` being a directory not a file
**Checklist**

[rtorrent-flood] fix rtorrentrc configmap

---

charts/stable/rtorrent-flood/Chart.yaml
charts/stable/rtorrent-flood/README.md
charts/stable/rtorrent-flood/values.yaml

The latest version of rtorrent-flood now can work with envars, I have removed the args.
**Checklist**

[rtorrent-flood] update chart to reflect latest Docker image version

---

charts/stable/home-assistant/Chart.yaml

This change fixes the missing "stable" folder in the chart.yaml sources section for home-assistant.
**Checklist**

[home-assistant] Fixed broken chart sources URL

---

charts/stable/bitwardenrs/Chart.yaml
charts/stable/bitwardenrs/README.md
charts/stable/bitwardenrs/README_CHANGELOG.md.gotmpl
charts/stable/bitwardenrs/templates/deployment-ldapsync.yaml

**Benefits**
- fixes #
**Checklist**

[bitwardenrs] Update var name and chart patch ver

---

charts/stable/blocky/Chart.yaml
charts/stable/blocky/values.yaml

Prior to the migration of blocky to the common chart, it used the default kubernetes deployment strategy of `RollingUpdate` which is (IMO) appropriate and desired for stateless workloads so as to not disrupt service when changes are applied.
This change will restore the default behavior of the blocky chart to RollingUpdate as it was prior to the migration to the common library chart.
**Benefits**
This allows for updates to blocky to happen in a rolling fashion so as to not disrupt service which can happen with `Recreate`.  As this serves DNS, this is especially important.
You need to wait longer for a multi-replica rollout to complete.
**Checklist**

[blocky] - default strategy should be RollingUpdate

---

charts/stable/bitwardenrs/Chart.yaml
charts/stable/bitwardenrs/templates/configmap.yaml

**Adding the support of SMTP password**
**Benefits**
If not set, we cannot use SMTP with authentication
**Checklist**

[bitwardenrs] [FIX] Add SMTP password

---

charts/stable/speedtest-prometheus/Chart.yaml
charts/stable/speedtest-prometheus/README.md
charts/stable/speedtest-prometheus/README_CHANGELOG.md.gotmpl
charts/stable/speedtest-prometheus/templates/servicemonitor.yaml
charts/stable/speedtest-prometheus/values.yaml

Signed-off-by: Julen Dixneuf <julend@padok.fr>
When I first installed the current speedtest-prometheus chart, I was unable to collect metrics, since my Prometheus only watch the serviceMonitors on the monitoring namespace (default behavior, at least for kube-prometheus-stack). In `values.yaml`, it seems that the variable `serviceMonitor.namespace` can be set, but the logic was not implemented.
I've just added the possibility to deploy the serviceMonitor on another namespace than the release.
**Benefits**
More flexibility when deploying such a component. Also it's a common feature for helm chart with service monitors.
I don't think I've done any breaking change.
Nope.
I have tested the new …

[speedtest-prometheus] feat: add namespace selection for serviceMonitor

---

charts/stable/bitwardenrs/Chart.yaml
charts/stable/bitwardenrs/README.md
charts/stable/bitwardenrs/templates/ingress.yaml

Fix prior PR
**Benefits**
none
**Checklist**

[bitwardenrs] Fix else spacing on Ingress

---

charts/stable/promcord/Chart.yaml
charts/stable/promcord/README.md
charts/stable/promcord/README_CHANGELOG.md.gotmpl
charts/stable/promcord/templates/podmonitor.yaml
charts/stable/promcord/values.yaml

Added a Service
**Benefits**
Adds a named port for the PodMonitor to function as intended
**Checklist**

[promcord] add service and servicemonitor

---

charts/stable/speedtest-prometheus/Chart.yaml

Superseeded by https://github.com/k8s-at-home/charts/tree/master/charts/stable/speedtest-exporter
**Checklist**

[speedtest-prometheus] deprecate chart

---

charts/stable/dnsmadeeasy-webhook/Chart.yaml
charts/stable/dnsmadeeasy-webhook/README.md
charts/stable/dnsmadeeasy-webhook/README_CHANGELOG.md.gotmpl
charts/stable/dnsmadeeasy-webhook/templates/rbac.yaml
charts/stable/dnsmadeeasy-webhook/values.yaml

Before this fix the deployed container was using the default service account and not the created one. This fix this and also uses the common chart to generate it.
**Benefits**
Works with RBAC
NA
NA
**Checklist**

[dnsmadeeasy-webhook] Fix to use created serviceaccount

---

charts/stable/sharry/Chart.yaml
charts/stable/sharry/README.md
charts/stable/sharry/templates/common.yaml
charts/stable/sharry/templates/configmap.yaml
charts/stable/sharry/values.yaml

Use a config block for sharry and some clean up
**Benefits**
Fixes a security issue where using the chart would always expose admin:admin account
without the ability to disable it.
User has to dig a bit in the configuration to configure authentication
N/A
I've tried to do a bit of clean up along the way, there may be a :bug: 
**Checklist**

[sharry] use a config blockk

---

charts/stable/wallabag/Chart.yaml
charts/stable/wallabag/README.md
charts/stable/wallabag/values.yaml

Add dependency charts for postgresql, mariadb and redis to wallabag
**Benefits**
Easier installation
N/A
N/A
**Checklist**

[wallabag] add dependency charts

---

.github/workflows/charts-lint-test.yaml
.github/workflows/charts-release.yaml

- Removes the check_version step from the CI
- Removes turnstyle in favor of Github's official concurrency
**Benefits**
- Removes the 100's of jobs that are spawned by the job matrix. Since we don't often have incubator charts, I don't think we are at risk of missing any incorrect version numbers during PR review.
- Removes dependency on turnstyle action. Using the official Github supported way should be favored.
- We are still human, so we might miss an incorrect version number during PR review sometime...
- Github concurrency is still in beta and might change a bit over time. Worked fine so far during testing

[CI] Remove check-version, turnstyle

---

charts/stable/bitwardenrs/Chart.yaml
charts/stable/bitwardenrs/README_CHANGELOG.md.gotmpl

This PR deprecates the bitwarden_rs chart in favor of the new vaultwarden chart.
However: In stark contrast with previous deprecations, I suggest keeping it active for a few months to ease people moving over to the vaultwarden chart.
**Benefits**
- promotes using the new name for bitwarden_rs (vaultwarden)
- promotes using a chart which uses the library chart
- deprecates a much used chart
- fixes #892
**Checklist**

[bitwarden_rs] Deprecate Bitwarden_rs chart

---

charts/stable/appdaemon/Chart.yaml
charts/stable/appdaemon/README.md
charts/stable/appdaemon/README.md.gotmpl
charts/stable/appdaemon/README_CHANGELOG.md.gotmpl
charts/stable/appdaemon/values.yaml

- Add `persistence.config.mountPath`
- Removed commented items in persistence.
**Benefits**
- fixes #899
- Bumped to major version because adding the `mountPath` might break existing installations? Advice on this is welcome.
**Checklist**

[appdaemon] Add persistence.config.mountPath

---

.github/workflows/incomplete-pr.yaml

Adds `incomplete-pr` workflow that automatically adds a comment asking to bump the chart version and run helm-docs. Triggered when `king:incomplete-pr` label is applied.
**Benefits**
- fixes #

[workflow] Add incomplete-pr [ci-skip]

---

charts/stable/oauth2-proxy/Chart.yaml
charts/stable/oauth2-proxy/README.md
charts/stable/oauth2-proxy/README.md.gotmpl
charts/stable/oauth2-proxy/README_CHANGELOG.md.gotmpl
charts/stable/oauth2-proxy/README_CONFIG.md.gotmpl
charts/stable/oauth2-proxy/values.yaml

oauth2-proxy was moved under the oauth2-proxy organization.
This pull request fixes outdated oauth2-proxy urls.
**Benefits**
People can visit new oauth2-proxy website and repository, not 404.
None (maybe)
None.
**Checklist**

[oauth2-proxy] Update oauth2-proxy website urls

---

charts/stable/syncthing/Chart.yaml
charts/stable/syncthing/README.md
charts/stable/syncthing/README.md.gotmpl
charts/stable/syncthing/README_CHANGELOG.md.gotmpl
charts/stable/syncthing/values.yaml

This PR bumps the Syncthing container version to `1.16.1` and common chart dependency to `2.5.0`. 
**Benefits**
Updating to the most recent release of the container.
N/A
N/A
**Checklist**

[syncthing] Syncthing version bump

---

charts/stable/unifi/Chart.yaml
charts/stable/unifi/README.md
charts/stable/unifi/values.yaml

This removes set, but unused values from the unifi chart's `values.yaml` file.
**Benefits**
Reduces confusion about configuration not having any effects
None
None
**Checklist**

[unifi] fix: remove unused values

---

.github/ct-install.yaml
charts/stable/pod-gateway-setter/.helmignore
charts/stable/pod-gateway-setter/Chart.yaml
charts/stable/pod-gateway-setter/README.md
charts/stable/pod-gateway-setter/README.md.gotmpl
charts/stable/pod-gateway-setter/README_CHANGELOG.md.gotmpl
charts/stable/pod-gateway-setter/README_CONFIG.md.gotmpl
charts/stable/pod-gateway-setter/templates/NOTES.txt
charts/stable/pod-gateway-setter/templates/admissionregistration.yaml
charts/stable/pod-gateway-setter/templates/common.yaml
charts/stable/pod-gateway-setter/templates/pki.yaml
charts/stable/pod-gateway-setter/values.yaml

This chart installs a mutator webhook admission controller in order to change
the default gateway and DNS of selected pods. Pods are selected by
labeling their namespace as described in the README.
**Benefits**
Allow routing egress traffic of pods through a different gateway, such
as a VPN forwarder, traffic shapper, etc.
VPN forwarder will be provided as separated chart.
Another chart - more maintenance.
- fixes NA
**Checklist**

[pod-gateway-setter] add pod-gateway-setter

---

charts/stable/unifi/Chart.yaml
charts/stable/unifi/README.md
charts/stable/unifi/README_CHANGELOG.md.gotmpl
charts/stable/unifi/values.yaml

Consistently change the application version everywhere. Before this
change, the chart was reporting an `appVersion` that was not
reflecting the default tag used to deploy the application.
**Checklist** 
This is my first contribution to the project. Please, let me know if I should do something else :)

[unifi] Version bump to 6.2.25

---

charts/stable/syncthing/Chart.yaml
charts/stable/syncthing/README.md
charts/stable/syncthing/README_CHANGELOG.md.gotmpl
charts/stable/syncthing/values.yaml

Bump syncthing to `v1.17.0`
**Benefits**
Update to current release version. 
None. 
N/A
**Checklist**

[syncthing] feat: bump syncthing version and add maintainer

---

charts/stable/zigbee2mqtt/README.md

**added privileged flag to readme for clarity**
Just a little mention of the flag for anyone beeing confused, why the device cannot be opened.
**Benefits**
Well, it will be more clear and easier to find if it has been overlooked in the values.yaml.
none
none
none

added privileged flag to readme for clarity

---

charts/stable/zigbee2mqtt/Chart.yaml
charts/stable/zigbee2mqtt/README.md
charts/stable/zigbee2mqtt/README_CHANGELOG.md.gotmpl
charts/stable/zigbee2mqtt/README_CONFIG.md.gotmpl
charts/stable/zigbee2mqtt/ci/ct-values.yaml
charts/stable/zigbee2mqtt/templates/common.yaml
charts/stable/zigbee2mqtt/values.yaml

Upgrades `zigbee2mqtt` chart to the latest common library version.
**Benefits**
- fixes #
**Checklist**

[zigbee2mqtt] Migrate to common v3

---

charts/stable/zwave2mqtt/Chart.yaml

deprecate zwave2mqtt in favor of zwavejs2mqtt

[zwave2mqtt] deprecate chart

---

charts/stable/adguard-home/Chart.yaml
charts/stable/adguard-home/README_CHANGELOG.md.gotmpl
charts/stable/adguard-home/values.yaml

Fixes the default protocol for the UDP port.
**Benefits**
- fixes #
Intentionally did not regenerate README. Want to see if the CI does it now 😄 
**Checklist**

[adguard-home] Fix port

---

charts/stable/pod-gateway/Chart.yaml
charts/stable/pod-gateway/README.md
charts/stable/pod-gateway/README_CHANGELOG.md.gotmpl
charts/stable/pod-gateway/templates/common.yaml

**Benefits**
- fixes #
**Checklist**

[pod-gateway] fix pod-gateway service definition

---

charts/stable/zalando-postgres-cluster/CHANGELOG.md
charts/stable/zalando-postgres-cluster/Chart.yaml
charts/stable/zalando-postgres-cluster/README.md
charts/stable/zalando-postgres-cluster/templates/backupCronjob.yaml
charts/stable/zalando-postgres-cluster/values.yaml

Allow the dumpBackup to take options of the common lib-chart persistence volume.
**Benefits**
Additional settings for the backup volume
None: only minor update so compatible with old values.
- fixes NA
**Checklist**

[zalando-postgres-cluster ] Enable additional settings for dumpBackup

---

charts/stable/pod-gateway/Chart.yaml
charts/stable/pod-gateway/templates/webhook-deployment.yaml

Remove one of the `strategy:` definitions in webhook-deployment.yaml. This was causing validation errors when installing.
**Benefits**
Chart should pass helm/kubectl validator now.
- fixes #
**Checklist**

[pod-gateway] Fix bug with duplicate strategy definitions in webhook-deployment.yaml

---

charts/stable/multus/Chart.yaml
charts/stable/multus/README.md
charts/stable/multus/README_CHANGELOG.md.gotmpl
charts/stable/multus/values.yaml

Another typo - cni version was not set correctly (wrong number of spaces).
Chart boots but then it is not able to provision new pods.
**Benefits**
- fixes #
**Checklist**

[multus] Set cni version in values.yaml

---

charts/stable/airsonic/Chart.yaml
charts/stable/airsonic/README.md
charts/stable/airsonic/README_CHANGELOG.md.gotmpl
charts/stable/airsonic/values.yaml

Use `airsonic-advanced` instead of linuxserver airsonic image
**Benefits**
Better featureset
No specific image versions are available for the current codebase, so tagged a specific digest.
- fixes #1058 
**Checklist**

[airsonic] Use airsonic-advanced

---

charts/stable/joplin-server/Chart.yaml
charts/stable/joplin-server/README.md
charts/stable/joplin-server/README_CHANGELOG.md.gotmpl
charts/stable/joplin-server/values.yaml

Update version of Joplin Server to 2.1.2 (Latest Stable Version)
**Benefits**
Joplin recently went through a major breaking change post-2.0. Updating the server will ensure users are able to continue to use this chart.
No foreseeable drawbacks
None
None
**Checklist**

joplin-server Bump version of Joplin Server to 2.1.2 (Latest Stable Version)

---

charts/stable/pod-gateway/Chart.yaml
charts/stable/pod-gateway/README.md
charts/stable/pod-gateway/README_CHANGELOG.md.gotmpl
charts/stable/pod-gateway/values.yaml

Because the default values.yaml file has `configFileSecret` set to `openvpn` by default, it is impossible to use the built in `configFile` with no secret. If you attempt to override `configFileSecret` to `null` the default value takes precedence, and the gateway will not start because of the lack of `openvpn` secret. 
**Benefits**
- fixes #
**Checklist**

[pod-gateway] Fix issue where values.yaml defined 'configFile' wouldn't work in vpn addon

---

charts/stable/ser2sock/Chart.yaml
charts/stable/ser2sock/README.md
charts/stable/ser2sock/README_CHANGELOG.md.gotmpl
charts/stable/ser2sock/values.yaml

Currently the env var references the host path instead of the path inside the container.
**Benefits**
n/a
n/a
n/a
**Checklist**

[ser2sock] Fix wrong device path

---

charts/stable/oauth2-proxy/Chart.yaml
charts/stable/oauth2-proxy/README_CHANGELOG.md.gotmpl
charts/stable/oauth2-proxy/values.yaml

Signed-off-by: Jan-Otto Kröpke <joe@adorsys.de>
oauth2-proxy to 7.1.3
**Benefits**
An up2date oauth2-proxy 
Unknown incompatibilities in oauth2-proxy 
**Checklist**

[oauth2-proxy] bump oauth2-proxy to 7.1.3

---

charts/stable/blocky/Chart.yaml
charts/stable/blocky/README.md
charts/stable/blocky/values.yaml

Signed-off-by: Brandon Clifford <brandon@clifford.sh>
This moves the `replicas` underneath `controller` as the move to the current common chart expects it here.
**Benefits**
Update's self-documentation mentioned in the values.yaml to indicate where replicas should be defined.
**Checklist**

[blocky] Move replicas under controller definition in values.yaml

---

charts/stable/pod-gateway/Chart.yaml
charts/stable/pod-gateway/README.md
charts/stable/pod-gateway/README_CHANGELOG.md.gotmpl
charts/stable/pod-gateway/templates/webhook-admissionregistration.yaml
charts/stable/pod-gateway/values.yaml

Currently `namespaceSelector` is defined as a dict to match k8s format, however this causes an issue if one wants to set a custom namespace label as Helm merges the values ending up with multiple labels.
This change allows setting custom labels that won't be merged, while still allowing complex custom selectors if needed.
**Benefits**
Fixes implementation to work as originally intended.
Breaking change for users that have already attempted to use custom `namespaceSelector`s (probably just me :) )
**Checklist**

[pod-gateway] Fix for allowing custom namespace selectors without dict merges

---

charts/stable/youtubedl-material/Chart.yaml
charts/stable/youtubedl-material/README.md
charts/stable/youtubedl-material/README_CHANGELOG.md.gotmpl
charts/stable/youtubedl-material/values.yaml

The change updates the pv mount paths to what I believe to be the correct paths. The app reads subscriptions from `/app/subscriptions`, videos from `/app/videos`, audio from `/app/audio` and config from `/app/appdata`. The way that the mount paths are written in the values.yaml, the volumes for subscriptions and video mount at the root directory instead of under /app.
I noticed there was a discrepancy with the mount paths when my videos were gone due to a pod eviction. The eviction was due to an exceeded ephemeral storage limit which makes sense because I was unknowingly storing videos within the container. 
As a workaround, I'm currently passing the mountPaths as values to my installation and I'm able to persist videos and audio as expected. 
**Benefits** …

[youtubedl-material] Fix incorrect mount paths

---

charts/stable/smarter-device-manager/Chart.yaml
charts/stable/smarter-device-manager/README.md
charts/stable/smarter-device-manager/README_CHANGELOG.md.gotmpl
charts/stable/smarter-device-manager/values.yaml

Signed-off-by: Andrew Zammit <zammit.andrew@gmail.com>
- Override the default container `terminationMessagePath` to allow mounting `/dev` as read-only. The path is now `/var/log/termination-log`. Fixes #1092.
- Use the container's error log to populate the container termination message, since smarter-device-manager does not support a k8s `termination-log`.
**Benefits**
The default `values.yaml` for this chart now work out-of-the-box.
This chart's `common` dependency was bumped on 8/12 to v4.0.0, which added support for the `termination` section. The default values added here may conflict with the consumer's expectation of behavior, albeit it never worked to begin with. If set by the consumer, these default values will have no effect. …

[smarter-device-manager] use /var/log for termination.messagePath (fixes #1092)

---

charts/stable/searx/Chart.yaml
charts/stable/searx/README.md
charts/stable/searx/README_CHANGELOG.md.gotmpl
charts/stable/searx/templates/common.yaml
charts/stable/searx/templates/configmap.yaml
charts/stable/searx/values.yaml

Modify Helm chart to support the latest version of Searx.
**Benefits**
* Latest version support, should allow for easier updating.
* Reindented Caddyfile
* Added option to disable automatic TLS in Caddy when using another Ingress in front of Caddy (like Traefik)
No real drawbacks.
**Checklist**

[searx] Update to latest version

---

charts/stable/lidarr/Chart.yaml
charts/stable/lidarr/README.md
charts/stable/lidarr/README_CHANGELOG.md.gotmpl
charts/stable/lidarr/ci/ct-exportarr-values.yaml
charts/stable/lidarr/templates/common.yaml
charts/stable/lidarr/templates/podmonitor.yaml
charts/stable/lidarr/values.yaml

If these changes look good I'll update sonarr and radarr as well.
**Checklist**

[lidarr] refactor of exportarr sidecar and podmonitor

---

charts/stable/lidarr/Chart.yaml
charts/stable/lidarr/README.md

Just a version to give it a little kickstart. The GitHub release was generated for 12.0.0, but never landed in the index.yaml. 
**Checklist**

[lidarr] version bump

---

charts/stable/speedtest-exporter/Chart.yaml
charts/stable/speedtest-exporter/README.md
charts/stable/speedtest-exporter/templates/servicemonitor.yaml
charts/stable/speedtest-exporter/values.yaml

Just bringing some consistency with metrics ports
**Checklist**

[speedtest-exporter] metrics consistency

---

charts/stable/home-assistant/Chart.yaml
charts/stable/home-assistant/README.md
charts/stable/home-assistant/README_CONFIG.md.gotmpl

update hass documentation for running behind a reverse proxy
**Benefits**
explain to ppl how to make hass work behind a reverse proxy
- fixes #1146
**Checklist**

[home-assistant] update hass documentation for running behind a reverse proxy

---

charts/stable/lidarr/Chart.yaml
charts/stable/lidarr/README.md
charts/stable/lidarr/templates/prometheusrules.yaml

[lidarr] fix rules

---

charts/stable/speedtest-exporter/Chart.yaml
charts/stable/speedtest-exporter/README.md
charts/stable/speedtest-exporter/templates/prometheusrules.yaml
charts/stable/speedtest-exporter/values.yaml

this should be the last
**Checklist**

[speedtest-exporter] fix rules

---

charts/stable/onedrive/Chart.yaml
charts/stable/onedrive/README.md
charts/stable/onedrive/README_CHANGELOG.md.gotmpl
charts/stable/onedrive/README_CONFIG.md.gotmpl
charts/stable/onedrive/ci/ct-values.yaml
charts/stable/onedrive/templates/common.yaml
charts/stable/onedrive/values.yaml

This update does the following: 
* Update chart documentation for env style authentication
* Now supports multi-arch (amd64 and arm64)
* Cleaned up depricated secrets
**Benefits**
Simpler install process which does not force a specific way of storing the secret which mean more flexibility to the end user. 
N/A
N/A
**Checklist**

[onedrive] Move to v2.0.1 of custom docker image

---

charts/stable/valheim/Chart.yaml
charts/stable/valheim/README.md
charts/stable/valheim/values.yaml

Moving to ghcr.io for the valheim-docker image, based on maintainers recommendation in [README.md](https://github.com/lloesche/valheim-server-docker).
**Benefits**
Will follow up to date images.
N/A
N/A
N/A
**Checklist**

[valheim] Update to use ghcr for image

---

charts/stable/zwavejs2mqtt/Chart.yaml
charts/stable/zwavejs2mqtt/README.md
charts/stable/zwavejs2mqtt/README_CHANGELOG.md.gotmpl
charts/stable/zwavejs2mqtt/values.yaml

Zwavejs2mqtt supports a [websocket server](https://zwave-js.github.io/zwavejs2mqtt/#/guide/homeassistant-official) for a dedicated [hass integration](https://www.home-assistant.io/integrations/zwave_js) that does not use mqtt.
**Benefits**
Use zwavejs2mqtt as websocket gateway
N/A
N/A
**Checklist**

[zwavejs2mqtt] Add websocket service

---

charts/stable/unifi/Chart.yaml
charts/stable/unifi/README.md
charts/stable/unifi/README_CHANGELOG.md.gotmpl
charts/stable/unifi/values.yaml

Moves the Traefik `serversscheme` annotations from the ingresses to the service.
**Benefits**
Makes the Unifi controller web portal available.
None that I'm aware of.
- N/A
Tested locally, confirmed that controller UI was not available prior to the change and is available afterwards.
**Checklist**

[unifi] Move traefik serversscheme annotations to service

---

charts/stable/vaultwarden/Chart.yaml
charts/stable/vaultwarden/README.md
charts/stable/vaultwarden/README_CHANGELOG.md.gotmpl
charts/stable/vaultwarden/values.yaml

Signed-off-by: Simon Caron <simon.caron@protonmail.com>
Bump vaultwarden/server to 1.22.2
**Benefits**
Update to the [latest release](https://github.com/dani-garcia/vaultwarden/releases/tag/1.22.2) to get security/bug fixes
N/A
N/A
**Checklist**

[vaultwarden] Bumped vaultwarden/server to 1.22.2

---

charts/stable/home-assistant/Chart.yaml
charts/stable/home-assistant/README.md
charts/stable/home-assistant/README_CHANGELOG.md.gotmpl
charts/stable/home-assistant/README_CONFIG.md.gotmpl

Simple README.md change to fix the home-assistant ingress example.
**Benefits**
It provides a working ingress example which users can copy&paste with minimal changes needed (host name).
-
-
**Checklist** 
- [-] Variables are documented in the README.md (this can be done with using our helm-docs wrapper `./hack/gen-helm-docs.sh stable <chart>`)

[home-assistant] Fix home-assistant ingress example

---

charts/stable/tautulli/Chart.yaml
charts/stable/tautulli/README.md
charts/stable/tautulli/README_CHANGELOG.md.gotmpl
charts/stable/tautulli/values.yaml

Bumped image version to 2.7.7
**Checklist**

[tautuli] Image version bump 

---

charts/incubator/changedetection-io/Chart.yaml
charts/incubator/changedetection-io/README.md
charts/incubator/changedetection-io/README_CHANGELOG.md.gotmpl
charts/incubator/changedetection-io/values.yaml

- Updated the image tag to v0.39.3
- Switched to GHCR
- Fixed `appVersion`
- Fixed changelog
- Updated readme
**Checklist**

[changedetection-io] Image version bump and fixes

---

charts/stable/mealie/Chart.yaml
charts/stable/mealie/README.md
charts/stable/mealie/README_CHANGELOG.md.gotmpl
charts/stable/mealie/values.yaml

Add Postgres DB to mealie -> https://hay-kot.github.io/mealie/documentation/getting-started/install/#docker-compose-with-postgres-beta
**Benefits**
Postgres instead of sqlite, having the benefit of not having it on each node.
**Checklist**

[mealie] - Support Postgres

---

charts/stable/tdarr/Chart.yaml
charts/stable/tdarr/README.md
charts/stable/tdarr/README_CHANGELOG.md.gotmpl
charts/stable/tdarr/templates/common.yaml
charts/stable/tdarr/values.yaml

Adding a shared persistence option to the tdarr node sidecar in order to
have a local (emptydir) alternative for transcodes between the server and node
containers.
Add option for shared directory between the tdarr server and node sidecar.
**Benefits**
Allow the option of a local emptydir transcode location 
n/a
n/a
**Checklist**

[tdarr] Add shared persistence to tdarr node sidecar

---

charts/stable/tdarr/Chart.yaml
charts/stable/tdarr/README.md
charts/stable/tdarr/README_CHANGELOG.md.gotmpl
charts/stable/tdarr/templates/common.yaml
charts/stable/tdarr/values.yaml

This change allows resources to be defined for the node container.
This change is useful for hardware passthrough to the node container.
**Benefits**
None
n/a
n/a
**Checklist**

[tdarr] Allow definition of resources for the node

---

charts/stable/onedrive/Chart.yaml
charts/stable/onedrive/README.md
charts/stable/onedrive/README_CHANGELOG.md.gotmpl
charts/stable/onedrive/values.yaml

Bump docker image to 2.0.5, which removes the patch being applied to source but retains a multi-arch image. Next release of onedrive may remove the custom image as there is a PR for multi-arch pending upstream. 
**Benefits**
Removed patch step on source code. 
N/A
N/A
N/A
**Checklist**

[onedrive] Bump image tag to 2.0.5

---

charts/stable/unifi/Chart.yaml
charts/stable/unifi/README.md
charts/stable/unifi/README_CHANGELOG.md.gotmpl
charts/stable/unifi/values.yaml

- Bump unifi version to 6.5.54
**Checklist**

[unifi] Update AppVersion to v6.5.54

---

charts/stable/tdarr/Chart.yaml
charts/stable/tdarr/README.md
charts/stable/tdarr/README_CHANGELOG.md.gotmpl
charts/stable/tdarr/templates/common.yaml
charts/stable/tdarr/values.yaml

This change adds and environment override for `ffmpegPath`. If unset, the
tdarr node container will use the default binary that ships with tdarr.
Using `""` may cause detection issues with hardware passthrough (`i915`),
but will remain backwards compatible with the container default.
**Benefits**
Allow overriding to the default system ffmpeg binary.
None.
n/a
This issue was discussed at length with the container maintainer and is the best solution to override the default ffmpeg binary which has vaapi detection problems.
**Checklist**

[tdarr] Add ffmpegPath environment override

---

charts/stable/lidarr/Chart.yaml
charts/stable/lidarr/README.md
charts/stable/lidarr/values.yaml
charts/stable/radarr/Chart.yaml
charts/stable/radarr/README.md
charts/stable/radarr/values.yaml
charts/stable/sonarr/Chart.yaml
charts/stable/sonarr/README.md
charts/stable/sonarr/values.yaml

Changes Made:
- Update patch level of radarr/sonarr/lidarr chart versions
- Update the exportarr container image from v0.6.1 -> v0.6.2
This patch resolves an issue when exportarr reads config.xml but the UrlBase property is empty.
This is tested and confirmed resolution in my environment.
Previous malformed URL in logs (v0.6.1)
```
exporter time="2021-12-16T18:26:22Z" level=info msg="Sending HTTP request to http://localhost:8989//api/v3/queue?page=1"
```
with the v.0.6.2 patch
```
exporter time="2021-12-16T20:18:12Z" level=info msg="Sending HTTP request to http://localhost:8989/api/v3/queue?page=1"
```

[lidarr/sonarr/radarr] Updating the exportarr image patch level

---

charts/stable/vaultwarden/Chart.yaml
charts/stable/vaultwarden/README.md
charts/stable/vaultwarden/README_CHANGELOG.md.gotmpl
charts/stable/vaultwarden/values.yaml

DRY a bit ports setup in ingress.
**Benefits**
When changing port number in service ( for example to run as non root ). User is also required to override ingress ports setup. This can be avoided if we use port name.
- fixes #
**Checklist**

[vaultwarden] Use port names in ingress setup

---

charts/stable/mealie/Chart.yaml
charts/stable/mealie/README.md
charts/stable/mealie/values.yaml

The subchart postgresql had a typo  in values file,  this was creating postgresql even though its off by default.
**Benefits**
The values file is fixed. The postgresql will created only when enabled=true in values file
None
- fixes #
**Checklist**

[mealie] Fix postgresql subchart name

---

charts/incubator/openhab/Chart.yaml
charts/incubator/openhab/README.md
charts/incubator/openhab/values.yaml

update to the latest stable openhab version 3.2.0
**Checklist**

[openhab] update to openhab 3.2.0

---

charts/stable/blocky/Chart.yaml
charts/stable/blocky/README.md
charts/stable/blocky/README_CHANGELOG.md.gotmpl
charts/stable/blocky/templates/servicemonitor.yaml
charts/stable/blocky/values.yaml

This PR updates the Blocky chart to use the latest released application version ([v0.17](https://github.com/0xERR0R/blocky/releases/tag/v0.17)). 
It also add support for the `jobLabel`, `targetLabels`, and `podTargetLabels` fields on the Prometheus service monitor.
**Benefits**
Bring the Helm chart up to date with the latest Blocky documentation to avoid confusion. This also enables new Blocky features including more control over caching, logging, and blocklists.
The `jobLabel`, `targetLabels`, and `podTargetLabels` fields on the Prometheus service monitor allow more control over how metrics are labeled, for example align with the conventions used in the [Blocky dashboard for Grafana](https://grafana.com/grafana/dashboards/13768).
See …

[blocky] update to blocky v0.17

---

charts/stable/frigate/Chart.yaml
charts/stable/frigate/README.md
charts/stable/frigate/README_CHANGELOG.md.gotmpl
charts/stable/frigate/ci/ct-values.yaml
charts/stable/frigate/values.yaml

This PR bumps frigate version to 0.9.4 and the chart-version to 7.0.0 as frigate introduced breaking changes to the config file. README.md is adjusted accordingly
**Benefits**
I just started installing frigate and there was a big mismatch between frigate documentation of configuration and the one needed for the version used in this chart. The new frigate version also includes better error messages for missing configuration, which should make the upgrade easy.
Most of my configuration errors were based on custom camera configuration.
*v0.8.x*
```
...
camera:
width: 640
height: 360
fps: 4
...
```
*v0.9.x*
```
...
camera:
detect:
width: 640
height: 360
fps: 4
...
```
**Checklist**

[frigate] update frigate version to 0.9.4

---

charts/incubator/cryptpad/Chart.yaml
charts/incubator/cryptpad/values.yaml

As per https://github.com/xwiki-labs/cryptpad-docker/blob/72dd7030c1dc1c70b5ff3f53b8451f5af19a2927/Dockerfile-nginx#L25, the docker image for Cryptpad will spawn the cryptpad process with a non-root user: https://github.com/xwiki-labs/cryptpad-docker/blob/72dd7030c1dc1c70b5ff3f53b8451f5af19a2927/supervisord.conf#L26
Such unprivileged user will not be able to write in persistence volumes, which are mounted as root. To work around this, we set the fsGroup in accordance with what supervisord already does inside the image.
**Benefits**
This will allow the chart to work when the volumes are mounted with restrictive permissions.
I did not notice this during testing as I was using an `emptyDir`, which gets mounted with `0777` by default 😞  …

[cryptpad] add default podSecurityContext

---

charts/stable/blocky/Chart.yaml
charts/stable/blocky/README.md
charts/stable/blocky/README_CHANGELOG.md.gotmpl
charts/stable/blocky/values.yaml

It's possible that when this chart was first built, container images (or multi-arch images) were not available - but they are now. See https://github.com/0xERR0R/blocky/pkgs/container/blocky for images that include amd64, arm64, arm/v6, and arm/v7.
This change changes the blocky helm chart to use container images built by the app maintainer.
**Benefits**
Container images direct from the source are published sooner and theoretically more reliable.
unknown?
- fixes #
**Checklist**

[blocky] use container image direct from the application developer

---

charts/stable/webtrees/.helmignore
charts/stable/webtrees/Chart.yaml
charts/stable/webtrees/README.md
charts/stable/webtrees/README.md.gotmpl
charts/stable/webtrees/README_CHANGELOG.md.gotmpl
charts/stable/webtrees/README_CONFIG.md.gotmpl
charts/stable/webtrees/ci/ct-values.yaml
charts/stable/webtrees/templates/NOTES.txt
charts/stable/webtrees/templates/common.yaml
charts/stable/webtrees/values.yaml

Add new chart for Open-source online collaborative genealogy application [(Webtrees)](https://www.webtrees.net/)
**Benefits**
The ability to deploy webtrees as a helm chart
None
- fixes #
**Checklist**

[webtrees] Add new chart

---

charts/incubator/dendrite/.helmignore
charts/incubator/dendrite/Chart.yaml
charts/incubator/dendrite/README.md
charts/incubator/dendrite/README.md.gotmpl
charts/incubator/dendrite/README_CHANGELOG.md.gotmpl
charts/incubator/dendrite/README_CONFIG.md.gotmpl
charts/incubator/dendrite/ci/ct-values.yaml
charts/incubator/dendrite/templates/NOTES.txt
charts/incubator/dendrite/templates/common.yaml
charts/incubator/dendrite/templates/dendrite-config.yaml
charts/incubator/dendrite/values.yaml

This is the initial version of a Dendrite helm chart that supports monolithic deployment.
Adds a new chart for deploying [Dendrite](https://github.com/matrix-org/dendrite), a matrix homeserver. 
It only supports the monolithic deployment but the dendrite installation documentation states:
> For most deployments, it is recommended to run in monolith mode with PostgreSQL databases.
**Benefits**
- Easy configuration use the values.yaml file
- Quick to install
- No support for polylith deployments
- Closes #1269 
**Checklist**

[dendrite] Add dendrite helm chart

---

charts/stable/node-red/Chart.yaml
charts/stable/node-red/README.md
charts/stable/node-red/README_CHANGELOG.md.gotmpl
charts/stable/node-red/values.yaml

Upgrades Node Red to 2.1.4.
**Benefits**
Latest version!  Bug fixes.
No known breaking changes, but is a major upstream version change.
Related PR https://github.com/k8s-at-home/charts/pull/1351 to supply a 1.3.x latest patch version.
**Checklist**

[node-red] Upgrade to 2.1.4.

---

charts/incubator/dendrite/Chart.yaml
charts/incubator/dendrite/README.md
charts/incubator/dendrite/templates/common.yaml
charts/incubator/dendrite/templates/postgresql-initdb.yaml
charts/incubator/dendrite/values.yaml

Fix the init scripts for postgresql in the dendrite chart.
**Benefits**
- Using postgres now works as the initialisation scripts are correctly loaded
- Init scripts are parameterized and use the `postgresqlUsername` values instead of hardcoded "dendrite"
- Databases initialised with postgres before version 14 that somehow go around no init scripts will need to update their database to verion 14
- N/A, no issue was created
**Checklist**

[dendrite] Fix postgresql init scripts for dendrite

---

charts/stable/unifi/Chart.yaml
charts/stable/unifi/README.md
charts/stable/unifi/values.yaml

Signed-off-by: Rickard Schoultz <rickard.schoultz@gmail.com>
unifi image upgraded from v6.5.54 to v6.5.55, per request urged by the unifi repo maintainer.
**Benefits**
Earlier versions than 6.5.55 are subject a remote code execution vulnerability (CVE-2021-44228 as well as CVE-2021-45046).
N/A
- fixes #1382
N/A
**Checklist**

[unifi] Upgraded unifi image to version 6.5.55.

---

charts/stable/ghost/Chart.yaml
charts/stable/ghost/README.md
charts/stable/ghost/values.yaml

Fixed the database string in values to work out of the box
**Benefits**
Better out-of-the-box experience.
I was unable to generate helm docs.
```
./hack/gen-helm-docs.sh stable ghost
-] Copying templates to /home/sky/Github/k8s-at-home-charts/charts/stable/ghost
INFO[2022-01-23T13:18:58+02:00] Found Chart directories [.]                  
INFO[2022-01-23T13:18:58+02:00] Generating README Documentation for chart /home/sky/Github/k8s-at-home-charts/charts/stable/ghost 
WARN[2022-01-23T13:18:58+02:00] Error generating gotemplates for chart /home/sky/Github/k8s-at-home-charts/charts/stable/ghost: template: /home/sky/Github/k8s-at-home-charts/charts/stable/ghost:120: function "fromYaml" not defined
```
**Checklist**

[ghost] Fix database string to match generated svc

---

charts/stable/maddy/Chart.yaml
charts/stable/maddy/README.md
charts/stable/maddy/files/maddy.conf
charts/stable/maddy/templates/common.yaml
charts/stable/maddy/values.yaml

- Enable configuring storage and imap backends
- Support for additional config files
- (disruptive change) Move alias files to `config_files `section
**Benefits**
More flexibility configuring email server
Disruptive change. It could be made concurrent but I would like to avoid keeping the glue code for the old name
- fixes NA
**Checklist**

[maddy] enable configuring storage and imap

---

charts/stable/vaultwarden/Chart.yaml
charts/stable/vaultwarden/README.md
charts/stable/vaultwarden/values.yaml

Upgrade the app version to 1.24.0.
**Benefits**
A newer version of the application will be installed.
**Checklist**

[vaultwarden] Upgrade app version to 1.24.0

---

charts/stable/puppeteer/Chart.yaml
charts/stable/puppeteer/README_CONFIG.md.gotmpl

Updating the readme until I can figure what chromium flags and/or headers are needed to connect from outside the cluster. 
**Checklist**

[puppeteer] update readme

---

charts/stable/sonarr/Chart.yaml
charts/stable/sonarr/README.md
charts/stable/sonarr/templates/common.yaml

If persistence.config.subPath is specified for the main Sonarr container and metrics is enabled, the exporter is unable to find /config/config.xml because the Deployment generated is missing the corresponding subPath entry.
This change adds the subpath if it is specified.
**Benefits**
Allows exporter container to find config.xml when values specified as:
persistence:
config:
enabled: true
existingClaim: media-config-lh-pvc
subPath: sonarr
None
See 
- fixes #1417 
**Checklist**

[sonarr] add metrics config subpath when config has subPath specified

---

charts/stable/lidarr/Chart.yaml
charts/stable/lidarr/README.md
charts/stable/lidarr/templates/common.yaml

If persistence.config.subPath is specified for the main Sonarr container and metrics is enabled, the exporter is unable to find /config/config.xml because the Deployment generated is missing the corresponding subPath entry.
This change adds the subpath if it is specified.
**Benefits**
Allows exporter container to find config.xml when values specified as:
persistence:
config:
enabled: true
existingClaim: media-config-lh-pvc
subPath: sonarr
None
#1417 
**Checklist**

[lidarr] add missing metrics subpath when persistence.config.subPath specified

---

charts/stable/radarr/Chart.yaml
charts/stable/radarr/README.md
charts/stable/radarr/templates/common.yaml

If persistence.config.subPath is specified for the main Sonarr container and metrics is enabled, the exporter is unable to find /config/config.xml because the Deployment generated is missing the corresponding subPath entry.
This change adds the subpath if it is specified.
**Benefits**
Allows exporter container to find config.xml when values specified as:
persistence:
config:
enabled: true
existingClaim: media-config-lh-pvc
subPath: sonarr
None
- fixes #1417 
**Checklist**

[radarr] add metrics config subpath when config has subPath specified

---

charts/stable/miniflux/Chart.yaml
charts/stable/miniflux/README.md
charts/stable/miniflux/values.yaml

Upgrade miniflux to version 2.0.35.
**Checklist**

[miniflux] Upgrade miniflux to version 2.0.35

---

charts/incubator/lancache/Chart.yaml
charts/incubator/lancache/templates/common.yaml
charts/incubator/lancache/values.yaml

Add probes for the LanCache DNS container.
**Benefits**
Improve DNS availability.
N/A
N/A
N/A
**Checklist**

[lancache] Add probes for LanCache DNS.

---

charts/stable/pod-gateway/Chart.yaml
charts/stable/pod-gateway/templates/webhook-deployment.yaml
charts/stable/pod-gateway/values.yaml

Hey gang! pod-gateway is a work of genius! This PR introduces a small optional changes to allow the operator to alter the `DNSPolicy` on the mutated pod.
Why? In my use-case, I mutate pods which run initContainers, and these initContainers require working DNS / network connectivity. Without this change, the webhook will always apply `DNSPolicy: None` to the pod, and then explicitly specify the VXLAN gateway endpoint as the DNS server using `dnsConfig`. This only works when the sidecar is up though, and so breaks DNS resolution for initContainers.
If a user doesn't care about routing DNS traffic over the gateway, they can set `DNSPolicy: ClusterFirst`, which will effectively ignore the `dnsConfig` values, and cause the pod to use the clusterDNS (_which is …

[pod-gateway] Permit overriding DNSPolicy

---

charts/stable/blocky/Chart.yaml
charts/stable/blocky/values.yaml

Upgraded the chart to use appVersion from Chart rather than values by default.
**Benefits**
Easy of maintenance
Not sure if there is any
**Checklist**

[blocky]: Upgrade appVersion and use it from chart.

---

charts/stable/paperless/Chart.yaml
charts/stable/paperless/README.md
charts/stable/paperless/values.yaml

This switches to the community fork of paperless-ng. The tracking ticket in paperless-ngx is https://github.com/paperless-ngx/paperless-ngx/issues/68.
Please see the following references for the community discussion of the decision to fork:
* https://github.com/jonaswinkler/paperless-ng/issues/1599
* https://github.com/jonaswinkler/paperless-ng/issues/1632.
**Benefits**
Switch to the community maintained **paperless-ngx** fork.
None that I am aware of.
This is a non-breaking change for the paperless application itself, but as it changes the upstream, I've opted to bump the major version.
**Checklist**

[paperless] chore: switch to paperless-ngx project

---

charts/stable/photoprism/Chart.yaml
charts/stable/photoprism/README.md
charts/stable/photoprism/values.yaml

Add support for MariaDB database backend to Photoprism for increased app performance. The style of the change was copied from the Webtrees chart, which uses the Bitnami MariaDB chart. All options are passed to Photoprism by env vars.
The default behaviour has been retained (i.e. SQLite remains the default backend).
https://docs.photoprism.app/getting-started/config-options/#database-connection
**Benefits**
Photoprism will be able to use MariaDB as well as SQLite, which will offer better performance for large photo libraries.
None
I'm not sure if the `README.md` is partially generated by CI, but I documented the new params in `values.yaml` and also in `README.md` in case it wasn't automagically re-generated. …

[photoprism] Add MariaDB support to Photoprism

---

charts/incubator/warrior/.helmignore
charts/incubator/warrior/Chart.yaml
charts/incubator/warrior/README_CONFIG.md.gotmpl
charts/incubator/warrior/templates/NOTES.txt
charts/incubator/warrior/templates/common.yaml
charts/incubator/warrior/values.yaml

Adds the ArchiveTeam warrior appliance as a new chart.
**Benefits**
I could not find a Helm chart anywhere to deploy their container. Might as well add it using the k8s-at-home framework.
The image published is only tagged with 'latest'.
See here for any configuration of the container: https://github.com/ArchiveTeam/warrior-dockerfile

[warrior] New incubator chart for ArchiveTeam warrior

---

charts/stable/paperless/Chart.yaml
charts/stable/paperless/values.yaml

Upgrades to paperless-ngx 1.6.0
**Benefits**
Makes 1.6.0 available per default
None.
None.
This also sets the default value for `PAPERLESS_PORT` which is needed to not break with 1.6.0. Please check https://github.com/paperless-ngx/paperless-ngx/issues/264 for detailed information.
**Checklist**

[paperless] feat: upgrade to paperless-ngx 1.6.0

---

charts/stable/wikijs/Chart.yaml
charts/stable/wikijs/values.yaml

Signed-off-by: Gavin Mogan <git@gavinmogan.com>
Remove default env variables for wikijs
**Benefits**
Allows env variables to be populated by secrets
Anyone depending on the default values will have things break
- fixes #1455
**Checklist**

[wikijs] Remove default empty env variables for wikijs - fixes #1455

---

charts/stable/monica/Chart.yaml
charts/stable/monica/values.yaml

Remove default env variables for monica
**Benefits**
Allows env variables to be populated by secrets
Anyone depending on the default values will have things break
- related to #1455 (wikijs)
**Checklist**

[monica] Remove default empty env variables - along the same lines as #1455

---

charts/stable/influxdb-exporter/Chart.yaml
charts/stable/influxdb-exporter/templates/servicemonitor.yaml
charts/stable/influxdb-exporter/values.yaml

- Update image to 0.9.0 (Support ingestion from InfluxDB v2 clients)
- Change default UDP port (on some config it's not supported using the same port for TCP and UDP)
- Fix ServiceMonitor port name
**Checklist**

[influxdb-exporter] update img to 0.9.0, use other port for UDP

---

charts/stable/homebridge/Chart.yaml
charts/stable/homebridge/templates/common.yaml

Currently we allow configuration of `startup.sh` through the `config` stanza in `values.yaml`, however this file is mounted with default permissions and so is not actually executable and fails silently. This adds a `defaultMode` configuration to the volume config which ensures the file will be executable at startup. 
**Benefits**
Ensures users running Homebridge will be able to configure and execute the startup script through the Helm configuration (commonly used for bootstrapping things like setting NET_CAP on the node binary).
No drawbacks, as this fixes intended behaviour.
- fixes #1465
**Checklist**

chore(homebridge): Set permissions for startup.sh to be executable

---

charts/stable/uptime-kuma/Chart.yaml
charts/stable/uptime-kuma/values.yaml

- Update the version of uptime-kuma to 1.13.1
- Update the chart version to 1.2.0
**Benefits**
New version of application that contains multiple security fixes (in v1.11.4 and v1.12.1)
New version might not be stable.
**Checklist** 
- [-] ~~Variables have been documented in the `values.yaml` file.~~

uptime-kuma: update version to 1.13.1

---

charts/stable/home-assistant/Chart.yaml

Home Assistant image updated to 2022.4.0
**Benefits**
New upstream release. Check full release notes at: https://www.home-assistant.io/blog/2022/04/06/release-20224/ 
List of breaking changes: https://www.home-assistant.io/blog/2022/04/06/release-20224/#breaking-changes
None
N/A
**Checklist**

[home-assistant]  image update to 2022.4.0

---

charts/stable/paperless/Chart.yaml
charts/stable/paperless/values.yaml

Updated values.yaml to add user/pass environment variables. Took me a long time to find these variables, they really should be here for other people to find.
**Benefits**
Clear configuration docs
none I can think of
**Checklist**

[paperless] Updated values.yaml to add user/pass env

---

charts/stable/uptime-kuma/Chart.yaml

update appVersion to [1.14.0](https://github.com/louislam/uptime-kuma/releases/tag/1.14.0)
**Benefits**
new features and fixes
as usual, new application versions may contain new bugs.
**Checklist**

uptime-kuma: update appVersion to 1.14.0

---

charts/stable/bazarr/Chart.yaml
charts/stable/bazarr/README.md
charts/stable/bazarr/values.yaml

Updated the docker image to the latest version, 1.0.3
**Benefits**
Latest version of the app
Unknown backwards compatitibility issues?
NA
Not sure why their docker image version was changed from 0.x.x to 1.x.x. The change log shows a bot updating version and the changes dont appear to be backwards incompatible to me.
```
commit 6ef1615a30dd531870087953e49180169e419210 (tag: v1.0.0-ls132)
Author: LinuxServer-CI <ci@linuxserver.io>
Date:   Sun Oct 24 06:42:02 2021 +0200
Bot Updating Package Versions
commit 07c79854f98404a67ea93f21792ce06bb581a590 (tag: v1.0.0-ls131, tag: v0.9.9-ls131)
Author: LinuxServer-CI <ci@linuxserver.io>
Date: …
```

[bazarr] Updated Docker image to v1.0.3

---

charts/stable/miniflux/Chart.yaml
charts/stable/miniflux/README.md
charts/stable/miniflux/values.yaml

Upgrade miniflux to version 2.0.36.
**Checklist**

[miniflux] Upgrade miniflux to version 2.0.36

---

charts/stable/uptime-kuma/Chart.yaml

update appVersion to 1.15.0
https://github.com/louislam/uptime-kuma/releases/tag/1.15.0
**Benefits**
new version of app, fixes, freatures, ...
New versions can contain new bugs.
**Checklist**

uptime-kuma: update appVersion to 1.15.0

---

charts/stable/audiobookshelf/Chart.yaml
charts/stable/audiobookshelf/README.md
charts/stable/audiobookshelf/values.yaml

Updated the app version to the latest 2x release and changed default image repository to ghcr as the author has started pushing images there.
**Benefits**
* No more dockerhub pulls.
* Latest app version 2x
**Checklist**

[audiobookshelf] Bump app version and change default image repo to ghcr

---

charts/stable/paperless/Chart.yaml

Bump paperless-ngx to the latest release -> 1.7.0 
https://github.com/paperless-ngx/paperless-ngx/releases/tag/ngx-1.7.0
**Benefits**
New features and bugfixes
N/A
N/A
N/A
**Checklist**

paperless: Update appVersion to 1.7.0

---

charts/stable/tdarr/Chart.yaml
charts/stable/tdarr/README.md
charts/stable/tdarr/templates/common.yaml
charts/stable/tdarr/values.yaml

Simply changed the mountPath to a parameterized value so it lines up for media
**Benefits**
tdarr node mountPath will match the server and reduce the need for manual config outside yaml
If I didn't do it right, it'll break something
- fixes #
I was trying to parameterize all additional volumeMounts as well for each key in persistence besides the already accounted for ones, but my inexperience with go templates was slowing me down so I figured this is a good enough start
**Checklist** 
- [X ] Title of the PR starts with chart name (e.g. `[home-assistant]`)

[tdarr] Pass-through mountPath value

---

charts/stable/pod-gateway/Chart.yaml
charts/stable/pod-gateway/README.md
charts/stable/pod-gateway/values.yaml

Change default openvpn port to 1194 as this is the default for UDP.
**Benefits**
Be consistent: use matching default port for UDP.
Changing defaults might affect some users.
- fixes #1525
**Checklist**

[pod-gateway] Change default openvpn port to 1194

---

charts/stable/onedrive/Chart.yaml
charts/stable/onedrive/values.yaml

Bumping docker image version for OneDrive to v2.4.17. Docker image version now matches application version. 
**Benefits**
Latest code from upstream.
N/A
N/A
N/A
**Checklist**

[onedrive] Update docker image to v2.4.17

---

charts/stable/blocky/Chart.yaml
charts/stable/blocky/README.md
charts/stable/blocky/README_CONFIG.md.gotmpl
charts/stable/blocky/ci/ct-values.yaml
charts/stable/blocky/values.yaml

This updates the helm chart to support redis.
**Benefits**
It has been introduced in version 0.18 of blocky and is beneficial when using multiple replicas of blocky as the dns caches are synchronized and so are the blocky states.
The redis chart bumps the minimum required version of k8s to 1.19+.
The default service would not be created in this version as I have put enabled to false.
This is only required if someone needs access to the blocky api endpoint.
N/A
- fixes #
**Checklist**

[blocky] - Add redis

---

charts/stable/vikunja/Chart.yaml
charts/stable/vikunja/templates/configmap.yaml
charts/stable/vikunja/values.yaml

The value defined in the [template](https://github.com/k8s-at-home/charts/blob/master/charts/stable/vikunja/templates/configmap.yaml#L44) does not match the value in the [persistence](https://github.com/k8s-at-home/charts/blob/master/charts/stable/vikunja/templates/common.yaml#L18) so the mount doesn't work as expected.
This PR makes them match!
**Benefits**
Makes Vikunja Helm chart work as expected. 👍 
None
None
**Checklist**

[vikunja] Fix subpath in configmap to match persistence value

---

charts/stable/paperless/Chart.yaml
charts/stable/paperless/README.md

Bump version to 1.7.1
**Benefits**
Bugfixes
N/A
N/A
N/A
**Checklist**

[paperless] Bump to version 1.7.1

---

charts/stable/vaultwarden/Chart.yaml
charts/stable/vaultwarden/README.md
charts/stable/vaultwarden/values.yaml

Updated VaultWarden to the latest minor release 1.25.0.
**Benefits**
New feature!
N/A
N/A
N/A
**Checklist**

[vaultwarden] Bump Vaultwarden App Version to 1.25.0

---

charts/stable/uptime-kuma/Chart.yaml

update to 1.16.1
**Benefits**
new version, new bugfixes
new version, possibly newly introduced bugs
**Checklist**

uptime-kuma: update to 1.16.1

---

charts/incubator/dendrite/Chart.yaml
charts/incubator/dendrite/templates/dendrite-config.yaml
charts/incubator/dendrite/values.yaml

This change allows database configuration to be set for each of the sub-components of Dendrite.
**Benefits**
This enabled use-cases such as:
- Use of a database other than SQLite or the included postgresql deployment
- Configure a completely separate database target for each component
- Configure database connection parameters per component
None that I'm aware of. Backward compatibility is kept with the current logic.
N/A
N/A
**Checklist**

[dendrite] Per-component database settings

---

charts/stable/unifi/Chart.yaml

Bump unifi to v7.1.66
Chart version is bumped to `4.10.0` as we are going up a minor version
for the unifi app.
Signed-off-by: Noel Georgi <git@frezbo.dev>

chore: bump unifi to v7.1.66

---

charts/stable/unifi/Chart.yaml
charts/stable/unifi/values.yaml

Fix Unifi pod `fsGroup`
When CSI mounts the unifi data if the `fsGroup` is not set it would be
mointed as uid `0` and when the unifi process starts as uid `999`, it
won't be able to access the data, producing permission denied errors and
the app failing to start.
Fix the above issue by setting the right `fsGroup` as set by the default
environment variables.
Signed-off-by: Noel Georgi <git@frezbo.dev>

chore: fix unifi podsecurity context

---

.github/workflows/charts-changelog.yaml

Reverts k8s-at-home/charts#1614
This bump has broken our workflows for now - error message is 
`Run actions/setup-python@v[4](https://github.com/k8s-at-home/charts/runs/6824036699?check_suite_focus=true#step:3:5).0.0
Error: The specified python version file at: /home/runner/work/charts/charts/.python-version does not exist`
Related issue below still outstanding:
https://github.com/actions/setup-python/issues/421
At work so don't have time to troubleshoot, thinking we roll back until there's a bit more clarity on best upgrade path from codeownersat setup-python.

Revert "chore(deps): update actions/setup-python action to v4"

---

charts/stable/mosquitto/Chart.yaml
charts/stable/mosquitto/templates/configmap.yaml
charts/stable/mosquitto/values.yaml

Add per_listener_settings option
**Benefits**
- fixes #1516 
**Checklist**

[mosquitto] Add per_listener_settings option

---

charts/incubator/teamspeak/Chart.yaml
charts/incubator/teamspeak/templates/common.yaml
charts/incubator/teamspeak/values.yaml

You can now specify the remote of the metric exporter for the teamspeak chart, this allows you to use it when running on non-standard query ports which is currently not possible.
**Benefits**
You will now be able to use the metric exporter when running teamspeak on non-standard query ports.
N/A
N/A
N/A
**Checklist**

[teamspeak] feat: Can now change metric exporter remote

---

charts/stable/uptime-kuma/Chart.yaml

update-kuma appVersion increased to 1.17.0
**Benefits**
new version, bugfixes
new version might contain new bugs...
none
**Checklist** 
- [X ] Title of the PR starts with chart name (e.g. `[home-assistant]`)

uptime-kuma: update appVersion to 1.17.0 (chart version 1.3.4)

---

charts/stable/uptime-kuma/Chart.yaml

update-kuma appVersion increased to 1.17.1
**Benefits**
new version, bugfixes
new version might contain new bugs...
none
**Checklist**

uptime-kuma: update appVersion to 1.17.1 (chart version 1.3.5)

---

charts/stable/prometheus-nut-exporter/Chart.yaml
charts/stable/prometheus-nut-exporter/templates/servicemonitor.yaml

Fix endpoints in `ServiceMonitor`.
**Benefits**
Allow monitoring multiple NUT servers.
N/A
N/A
N/A
**Checklist**

[prometheus-nut-exporter] Fix service monitor.

---

charts/incubator/dendrite/Chart.yaml
charts/incubator/dendrite/ci/polylith-full-values.yaml
charts/incubator/dendrite/templates/dendrite-config.yaml
charts/incubator/dendrite/templates/ingress.yaml
charts/incubator/dendrite/values.yaml

Add an ingress configuration with correct routing for each polylith service.
**Benefits**
Reduces the toil in getting a polylith setup ready to go.
Config fixes may be breaking, although unlikely to be honest.
- closes #1600 
**Checklist**

[Dendrite] Polylith ingress and config fixes

---

charts/stable/pod-gateway/Chart.yaml
charts/stable/pod-gateway/templates/common.yaml
charts/stable/pod-gateway/values.yaml

Updates the default images used by pod-gateway to the latest ones.
**Benefits**
Users don't have to manually update the images to get the latest version.
- fixes #1684
**Checklist**

[pod-gateway]: Bump image versions

---

charts/stable/adguard-home/Chart.yaml
charts/stable/adguard-home/README.md
charts/stable/adguard-home/values.yaml

Upgrade to version v0.107.7. Synced configuration with the new version.
**Checklist**

[adguard-home] Upgrade to version v0.107.7

---

charts/stable/jackett/Chart.yaml
charts/stable/jackett/README.md

Signed-off-by: SurgeVortex <ac.chris.ackerman@gmail.com>
Bumping the container image version to v0.20.1316
**Benefits**
Having the latest version has possible fixes and / or improvements which may increase security or improve performance, etc.
There may be new bugs or regressions in the new version.
Closes #1704
**Checklist**

[jackett] Bumping jackett version to the latest stable version v0.20.1316

---

charts/stable/mosquitto/Chart.yaml
charts/stable/mosquitto/values.yaml

Previous title was `Update container image in values.yaml to v2.0.14`
https://github.com/k8s-at-home/charts/pull/1702 bumped the appVersion but not the actual value.
**Benefits**
Same as https://github.com/k8s-at-home/charts/pull/1702 
Same as https://github.com/k8s-at-home/charts/pull/1702 
none
none
**Checklist**

[mosquitto] Use appVersion as image tag by default

---

charts/stable/mosquitto/Chart.yaml
charts/stable/mosquitto/README.md
charts/stable/mosquitto/templates/configmap.yaml
charts/stable/mosquitto/values.yaml

Add an option to control adding of the `listener` option to mosquitto.conf. Using TLS in Mosquitto does not work if the `listener` option is present in the main mosquitto.conf. The linked issue has a longer description on the problem.
**Benefits**
TLS can be configured without having to manually edit the chart.
None, the change is fully backwards compatible.
- Fixes #1701
**Checklist** 
- [ X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/hel …

[mosquitto] Add option for selectively adding listener

---

charts/stable/unifi/Chart.yaml
charts/stable/unifi/README.md

Bump Unifi to [v7.1.68](https://github.com/jacobalberty/unifi-docker/releases/tag/v7.1.68)
Signed-off-by: Noel Georgi <git@frezbo.dev>

chore: bump unifi app to v7.1.68

---

charts/stable/onedrive/Chart.yaml
charts/stable/onedrive/values.yaml

This updates the app to 2.4.20 and replaces my image with the upstream image. 
**Benefits**
I don't have to build the image anymore, upstream supports arm now!
None known.
N/A
N/A
**Checklist**

[onedrive] Update to 2.4.20 and use upstream docker image

---

charts/stable/homer/Chart.yaml
charts/stable/homer/values.yaml

Signed-off-by: Pascal Iske <info@pascaliske.dev>
- Updated app version to `v22.07.2`
- The environment variables for asset permissions were removed and a security context object were configured for the correct file permissions of the apps assets.
**Benefits**
The code change allows the usage with newer app versions than `22.02.2`, e.g. `v22.06.1` and newer.
Custom values of users need to switch from env variables to security context as well.
- fixes #1713
**Checklist**

[homer]: update app version, switch to security context

---

charts/stable/mosquitto/Chart.yaml
charts/stable/mosquitto/README.md
charts/stable/mosquitto/values.yaml

Persistent storage settings for `configinc` have been removed because they should not have been there in the first place as they are to be specified by the user.
**Benefits**
The chart is aligned to the best practices used in this repository.
The user must now specify the storage manually.
**Checklist** 
- [ X] Title of the PR starts with chart name (e.g. `[home-assistant]`)
- [ X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [ X] Variables have been documented in the `values.yaml` file.

[mosquitto] Remove storage fields from configinc value

---

charts/stable/jellyfin/Chart.yaml
charts/stable/jellyfin/README.md
charts/stable/jellyfin/values.yaml

* Updates Jellyfin to 10.8.1
* Fixes typo in Chart.yaml homepage url (capital J instead of lower-case)
**Benefits**
* Updated version
* artifacthub.io homepage link will go to the right place now :)
N/A
N/A
Not sure if 10.7.7 to 10.8.1 would warrant bumping the chart minor version instead of patch, can change it if so
**Checklist**

[jellyfin] Update to 10.8.1 and fix typo in Chart.yaml homepage URL

---

charts/incubator/dendrite/Chart.yaml
charts/incubator/dendrite/values.yaml

Upgraded app version to 0.9.3 and changed to use ghcr.io.
**Benefits**
Will not hit Docker Hub rate limits and newer software.
**Checklist**

[dendrite] Upgrade app version and change default value to Github Containers
